title: Wannabil — Lanyon
description: Content-first, sliding sidebar theme
url: https://wannabil.github.io
remote_theme: poole/lanyon

plugins:
  - jekyll-remote-theme

markdown: kramdown
permalink: /:title/

